---
- hosts: localhost
  gather_facts: False

  vars_files:
    - ./vars/digitalocean_vault.yml
    - ./vars/digitalocean_vars.yml

  tasks:
    - name: Create a Droplet
      digital_ocean_droplet:
        state: present
        name: oliverdavies-uk
        oauth_token: '{{ digitalocean_api_key }}'
        size: 1gb
        region: lon1
        image: ubuntu-16-04-x64
        wait_timeout: 500
      register: droplet

    - debug: var=droplet
