---
- name: Download a database

  hosts: all

  vars_files:
    - vars/vars.yml

  vars:
    export_filename: /tmp/drupal.sql

  tasks:
    - name: Export the database
      command:
        cmd: >
          ../vendor/bin/drush sql-dump
          --gzip
          --result-file={{ export_filename }}
        chdir: "{{ project_root_path }}/{{ ansistrano_current_dir }}/{{ project_web_dir }}"
        creates: "{{ export_filename }}"

    - name: Fetch the database from the server
      fetch:
        src: "{{ export_filename }}.gz"
        dest: "{{ playbook_dir }}/../assets/development/"
        flat: true

    - name: Remove the export from the server
      file:
        path: "{{ export_filename }}.gz"
        state: absent
