all:
  children:
    db:
      hosts:
        64.227.46.2:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_port: 2849
        ansible_ssh_user: root
    web:
      hosts:
        64.227.46.2:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_port: 2849
        ansible_ssh_user: root
