version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase-if-necessary

  - package-ecosystem: npm
    directory: web/themes/custom/opdavies
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
