services:
  nginx:
    build:
      context: .
      target: nginx
    volumes:
      - assets:/app/web/themes/custom/opdavies/build
      - ./:/app
    depends_on:
      php:
        condition: service_started
    ports:
      - "${DOCKER_WEB_PORT:-127.0.0.1:80}:80"
    restart: unless-stopped

  php:
    build:
      context: .
      target: dev
    image: ghcr.io/opdavies/oliverdavies-uk-php:7.4-alpine
    volumes:
      - ./:/app
    env_file:
      - .docker.env
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    image: mariadb:10
    volumes:
      - "${DOCKER_MYSQL_VOLUME:-./db-data:/var/lib/mysql}"
      - ./tools/assets/development:/docker-entrypoint-initdb.d
    env_file:
      - .docker.env
    healthcheck:
      test: ["CMD-SHELL", "bash", "-c", "echo > /dev/tcp/localhost/3306"]
      interval: 1s
    restart: unless-stopped

volumes:
  assets:
  mysql_data:
