version: '2.4'

volumes:
  mysql_data:

services:
  nginx:
    image: nginx:stable
    working_dir: /app
    volumes:
      - ./:/app
      - ./tools/docker/images/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      node:
        condition: service_started
      php:
        condition: service_started

  php:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    environment:
      docker: "true"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mariadb:10
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    healthcheck:
      test: ["CMD-SHELL", "bash", "-c", "echo > /dev/tcp/localhost/3306"]
      interval: 1s

  node:
    image: node:12
    working_dir: /node
    volumes:
      - ./web:/node
