---
- name: Install Composer dependencies
  composer:
    command: install
    working_dir: '{{ ansistrano_release_path.stdout }}'

- name: Generate settings.php file
  include_role:
    name: opdavies.drupal_settings_files

- name: Import configuration
  command: '{{ release_drush_path }} config-import -y'
  args:
    chdir: '{{ release_web_path }}'

- name: Run database updates
  command: '{{ release_drush_path }} updatedb -y'
  args:
    chdir: '{{ release_web_path }}'

- name: Rebuild cache
  command: '{{ release_drush_path }} cache-rebuild'
  args:
    chdir: '{{ release_web_path }}'
