<?php

/**
 * @file
 * Functions to support theming in the Tailwind CSS theme.
 */

use Drupal\opdavies_blog\Entity\Node\Post;

/**
 * Implements hook_preprocess_HOOK().
 */
function opdavies_preprocess_page(array &$variables): void {
  /** @var Post|null $node */
  $node = $variables['node'] ?? NULL;
  if (!$node) {
    return;
  }

  if (!$node instanceof Post) {
    return;
  }

  if ($node->hasTweet()) {
    $variables['#attached']['library'][] = 'opdavies/twitter';
  }
}
