---
ansistrano_allow_anonymous_stats: false
ansistrano_deploy_via: git
ansistrano_deploy_to: '{{ project_root_path }}'
ansistrano_git_identity_key_path: '{{ playbook_dir }}/id_deploy'
ansistrano_git_repo: git@github.com:opdavies/oliverdavies-uk.git
ansistrano_git_branch: master
ansistrano_keep_releases: 5
ansistrano_shared_paths:
  - '{{ project_web_dir }}/sites/default/files'

# Hooks
ansistrano_after_symlink_shared_tasks_file: '{{ playbook_dir }}/deploy/after-symlink-shared.yml'
ansistrano_after_update_code_tasks_file: '{{ playbook_dir }}/deploy/after-update-code.yml'

app_hash_salt: '{{ vault_app_hash_salt }}'

release_drush_path: '{{ ansistrano_release_path.stdout }}/vendor/bin/drush'
release_web_path: '{{ ansistrano_release_path.stdout }}/{{ project_web_dir }}'

drupal_settings:
  - drupal_root: '{{ release_web_path }}'
    sites:
      - name: default
        filename: settings.local.php
        settings:
          hash_salt: '{{ app_hash_salt }}'
          databases:
            default:
              default:
                driver: mysql
                host: localhost
                database: oliverdavies_uk
                username: '{{ app_mysql_user }}'
                password: '{{ app_mysql_password }}'
          trusted_hosts:
            - '^d8\.oliverdavies\.uk$'
          extra_parameters: |
            $settings['config_exclude_modules'] = [
              'devel',
              'stage_file_proxy',
            ];
