module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  breakpoint: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  contextual: 0
  core_event_dispatcher: 0
  ctools: 0
  datetime: 0
  dblog: 0
  discoverable_entity_bundle_classes: 0
  dynamic_page_cache: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  honeypot: 0
  hook_event_dispatcher: 0
  hreflang: 0
  image: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  markdown: 0
  media: 0
  media_library: 0
  menu_trail_by_path: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  opdavies_blog: 0
  opdavies_recommendations: 0
  opdavies_talks: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  plausible: 0
  redirect: 0
  scheduler: 0
  shortcut: 0
  simple_sitemap: 0
  simple_sitemap_engines: 0
  simple_sitemap_views: 0
  speakerdeck_field: 0
  stage_file_proxy: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  claro: 0
  opdavies: 0
  gin: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
