entity_type_groups:
  node:
    page:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
    post:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
    talk:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
