version: 1

update_configs:
  - package_manager: php:composer
    directory: /
    update_schedule: weekly
    default_reviewers:
      - opdavies
    version_requirement_updates: 'off'

  - package_manager: javascript
    directory: web/themes/custom/opdavies
    update_schedule: weekly
    default_reviewers:
      - opdavies
    version_requirement_updates: 'off'
