confd('workspace:/tools/workspace/confd'):
  - { src: 'docker-compose.yaml', dst: 'workspace:/docker-compose.yaml' }
  - { src: 'Dockerfile', dst: 'workspace:/Dockerfile' }
  - { src: 'settings.local.php', dst: 'workspace:/web/sites/default/settings.local.php' }
  - { src: 'vhost.conf', dst: 'workspace:/tools/.docker/images/nginx/vhost.conf' }
