#!/usr/bin/env bash

## Description: Helper commands for the for theme
## Usage: app install|refresh

set -e

if [ $# -eq 0 ] ; then
  echo 'No arguments entered.'
  exit 1
fi

case $1 in
  install|refresh)
    drush site:install -y --account-pass=admin123 --existing-config
    drush user:login
    ;;

  *)
    echo "Invalid argument: $1"
    ;;
esac
