<?php

/**
 * @file
 * Custom module.
 */

declare(strict_types=1);

use Drupal\discoverable_entity_bundle_classes\Storage\Node\NodeStorage;

/**
 * Implements hook_entity_type_build().
 */
function custom_entity_type_build(array &$entityTypes): void {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entityTypes */
  if (isset($entityTypes['node'])) {
    $entityTypes['node']->setStorageClass(NodeStorage::class);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function custom_preprocess_block(array &$variables): void {
  // Add the 'markup' class to blocks.
  if (in_array($variables['plugin_id'], ['views_block:featured_blog_posts-block_1'])) {
    $variables['attributes']['class'][] = 'markup';
  }
}
